# Generated by Django 4.1 on 2024-11-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slider',
            new_name='Slide',
        ),
    ]
